// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dao} from '../models';

export function AddItem(arg1:string,arg2:number):Promise<void>;

export function AddOrder(arg1:Array<string>):Promise<void>;

export function AddPromotion(arg1:string,arg2:Array<string>):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteAllFiles():Promise<void>;

export function DeleteItem(arg1:number):Promise<string>;

export function DeleteOrder(arg1:number):Promise<number>;

export function DeletePromotion(arg1:number):Promise<string>;

export function GetItemByID(arg1:number):Promise<main.ItemDTO>;

export function GetItemByIDWithIndex(arg1:number):Promise<main.ItemDTO>;

export function GetItems():Promise<Array<main.ItemDTO>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetOrderByID(arg1:number):Promise<dao.OrderDTO>;

export function GetOrders():Promise<Array<dao.OrderDTO>>;

export function GetPromotionByID(arg1:number):Promise<dao.PromotionDTO>;

export function GetPromotions():Promise<Array<dao.PromotionDTO>>;

export function PopulateInventory(arg1:string):Promise<string>;

export function PrintBinaryFile():Promise<void>;

export function PrintIndex():Promise<void>;

export function PrintOrdersFile():Promise<void>;

export function PrintPromotionsFile():Promise<void>;

export function RebuildIndex():Promise<void>;
