// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddItem(arg1:string,arg2:number):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteAllFiles():Promise<void>;

export function GetLogs():Promise<Array<main.LogEntry>>;
