// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2) {
  return window['go']['main']['App']['AddItem'](arg1, arg2);
}

export function AddOrder(arg1) {
  return window['go']['main']['App']['AddOrder'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteAllFiles() {
  return window['go']['main']['App']['DeleteAllFiles']();
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function GetItemByID(arg1) {
  return window['go']['main']['App']['GetItemByID'](arg1);
}

export function GetItemByIDWithIndex(arg1) {
  return window['go']['main']['App']['GetItemByIDWithIndex'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOrderByID(arg1) {
  return window['go']['main']['App']['GetOrderByID'](arg1);
}

export function GetOrders() {
  return window['go']['main']['App']['GetOrders']();
}

export function PopulateInventory(arg1) {
  return window['go']['main']['App']['PopulateInventory'](arg1);
}

export function PrintBinaryFile() {
  return window['go']['main']['App']['PrintBinaryFile']();
}

export function PrintIndex() {
  return window['go']['main']['App']['PrintIndex']();
}

export function PrintOrdersFile() {
  return window['go']['main']['App']['PrintOrdersFile']();
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}
