// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2) {
  return window['go']['main']['App']['AddItem'](arg1, arg2);
}

export function ApplyPromotionToOrder(arg1, arg2) {
  return window['go']['main']['App']['ApplyPromotionToOrder'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateOrder(arg1, arg2) {
  return window['go']['main']['App']['CreateOrder'](arg1, arg2);
}

export function CreatePromotion(arg1, arg2) {
  return window['go']['main']['App']['CreatePromotion'](arg1, arg2);
}

export function DeleteAllFiles() {
  return window['go']['main']['App']['DeleteAllFiles']();
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function DeletePromotion(arg1) {
  return window['go']['main']['App']['DeletePromotion'](arg1);
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetAllOrders() {
  return window['go']['main']['App']['GetAllOrders']();
}

export function GetAllPromotions() {
  return window['go']['main']['App']['GetAllPromotions']();
}

export function GetIndexContents() {
  return window['go']['main']['App']['GetIndexContents']();
}

export function GetItem(arg1, arg2) {
  return window['go']['main']['App']['GetItem'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOrder(arg1) {
  return window['go']['main']['App']['GetOrder'](arg1);
}

export function GetOrderPromotions(arg1) {
  return window['go']['main']['App']['GetOrderPromotions'](arg1);
}

export function GetOrderWithPromotions(arg1) {
  return window['go']['main']['App']['GetOrderWithPromotions'](arg1);
}

export function GetPromotion(arg1) {
  return window['go']['main']['App']['GetPromotion'](arg1);
}

export function GetPromotionOrders(arg1) {
  return window['go']['main']['App']['GetPromotionOrders'](arg1);
}

export function PopulateInventory() {
  return window['go']['main']['App']['PopulateInventory']();
}

export function PopulatePromotions() {
  return window['go']['main']['App']['PopulatePromotions']();
}

export function RemovePromotionFromOrder(arg1, arg2) {
  return window['go']['main']['App']['RemovePromotionFromOrder'](arg1, arg2);
}
