// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1) {
  return window['go']['main']['App']['AddItem'](arg1);
}

export function DeleteAllFiles() {
  return window['go']['main']['App']['DeleteAllFiles']();
}

export function GetItemByID(arg1) {
  return window['go']['main']['App']['GetItemByID'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function PopulateInventory(arg1) {
  return window['go']['main']['App']['PopulateInventory'](arg1);
}

export function PrintBinaryFile() {
  return window['go']['main']['App']['PrintBinaryFile']();
}

export function PrintIndex() {
  return window['go']['main']['App']['PrintIndex']();
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}
