// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1:string):Promise<void>;

export function GetItems():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function PrintBinaryFile():Promise<void>;

export function ValidateBinaryFile():Promise<string>;
